name: HW06 LOCAL
values:
  - key: baseUrl
    value: ''
  - key: studentId
    value: ''
  - key: userToken
    value: ''
  - key: adminToken
    value: ''
  - key: runId
    value: ''
  - key: adminUserId
    value: ''
color: 120
